// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fall back to a local SQLite file if DATABASE_URL is not set in environment
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
